2018-01-17T14:07:57.0626651+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T14:08:00.9657833+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T14:08:01.2386554+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 323.5907ms 200 
2018-01-17T14:08:01.3896415+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:08:01.4836841+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 94.0795ms 200 
2018-01-17T14:12:03.3555014+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T14:12:06.2227622+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T14:12:06.2736474+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 61.2494ms 200 
2018-01-17T14:12:06.3416054+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:12:06.3479520+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 5.9434ms 200 
2018-01-17T14:12:11.7052396+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T14:12:11.7116896+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 6.4985ms 200 
2018-01-17T14:12:11.7368623+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:12:11.7580985+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 21.2498ms 200 
2018-01-17T14:12:21.4745123+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T14:12:21.4790986+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4.7398ms 200 
2018-01-17T14:12:21.4969926+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:12:21.5044426+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 7.449ms 200 
2018-01-17T14:13:53.8665128+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T14:13:57.6680050+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T14:13:57.8567390+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 208.4626ms 200 
2018-01-17T14:13:57.9305035+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:13:57.9491102+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 18.1201ms 200 
2018-01-17T14:14:03.4244586+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T14:14:03.5514842+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T14:14:03.5734377+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T14:14:10.0135272+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T14:14:10.0985634+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 6562.4355ms
2018-01-17T14:14:10.1090502+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 6684.5464ms 200 application/json; charset=utf-8
2018-01-17T14:14:10.1387800+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:14:10.1443506+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 5.6028ms 200 
2018-01-17T14:25:39.0473232+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T14:25:41.6400530+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T14:25:41.7262051+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 92.0544ms 200 
2018-01-17T14:25:41.7590523+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:25:41.7647882+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4.4899ms 200 
2018-01-17T14:25:48.1287926+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T14:25:48.1929191+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T14:25:48.2053649+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T14:25:52.6836643+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 4500.3894ms
2018-01-17T14:25:52.6939582+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__3.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-01-17T14:25:53.0100199+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4881.012ms 500 text/html; charset=utf-8
2018-01-17T14:25:53.0609991+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:25:53.1056555+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 44.6542ms 200 
2018-01-17T14:26:29.7884150+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T14:26:32.7792115+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T14:26:32.8648879+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 92.6552ms 200 
2018-01-17T14:26:32.9002585+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:26:32.9057591+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4.9155ms 200 
2018-01-17T14:26:35.7144145+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T14:26:35.7809054+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T14:26:35.7930594+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T14:26:39.3708539+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 3601.7893ms
2018-01-17T14:26:39.3841310+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__3.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-01-17T14:26:39.6720100+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 3956.9429ms 500 text/html; charset=utf-8
2018-01-17T14:26:39.7445557+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T14:26:39.7496391+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4.9273ms 200 
2018-01-17T14:26:53.8782273+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T14:26:53.8843589+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T14:26:53.8879062+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:08:33.4562241+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T15:08:36.2531997+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T15:08:36.3483077+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 101.1366ms 200 
2018-01-17T15:08:36.3818728+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:08:36.3875724+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 5.7378ms 200 
2018-01-17T15:08:39.2182754+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:13:28.6143055+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T15:13:32.0830758+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T15:13:32.1826817+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 105.6522ms 200 
2018-01-17T15:13:32.2194561+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:13:32.2247965+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 5.1148ms 200 
2018-01-17T15:13:43.2283415+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:13:46.0836165+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:13:46.0992760+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:13:53.9143235+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T15:13:53.9708264+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 10673.6219ms
2018-01-17T15:13:53.9752394+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 10746.9051ms 200 application/json; charset=utf-8
2018-01-17T15:13:53.9845358+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:13:53.9887116+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4.0742ms 200 
2018-01-17T15:27:02.5861742+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T15:27:05.3002346+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T15:27:05.3900538+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 95.5279ms 200 
2018-01-17T15:27:05.4301441+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:27:05.4367931+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 6.5087ms 200 
2018-01-17T15:28:05.0790468+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T15:28:07.9264037+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T15:28:08.0401124+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 113.4787ms 200 
2018-01-17T15:28:08.0839115+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:28:08.0888018+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4.6159ms 200 
2018-01-17T15:28:10.1153394+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:28:10.1822884+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:28:10.1963609+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:28:15.6754021+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:28:17.1232109+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:28:17.1536890+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:28:37.6694124+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 27488.6169ms
2018-01-17T15:28:37.6694124+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 20543.3233ms
2018-01-17T15:28:37.7324312+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.ArgumentOutOfRangeException: The SqlDbType enumeration value, 0, is invalid.
Parameter name: SqlDbType
   at System.Data.SqlClient.MetaType.GetSqlDataType(Int32 tdsType, UInt32 userType, Int32 length)
   at System.Data.SqlClient.TdsParser.TryCommonProcessMetaData(TdsParserStateObject stateObj, _SqlMetaData col)
   at System.Data.SqlClient.TdsParser.TryProcessMetaData(Int32 cColumns, TdsParserStateObject stateObj, _SqlMetaDataSet& metaData)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at SCPersonalizationGraph.Model.SQLDB.GetData() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Model\SQLDB.cs:line 27
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-01-17T15:28:37.7327845+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.ArgumentOutOfRangeException: The SqlDbType enumeration value, 0, is invalid.
Parameter name: SqlDbType
   at System.Data.SqlClient.MetaType.GetSqlDataType(Int32 tdsType, UInt32 userType, Int32 length)
   at System.Data.SqlClient.TdsParser.TryCommonProcessMetaData(TdsParserStateObject stateObj, _SqlMetaData col)
   at System.Data.SqlClient.TdsParser.TryProcessMetaData(Int32 cColumns, TdsParserStateObject stateObj, _SqlMetaDataSet& metaData)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at SCPersonalizationGraph.Model.SQLDB.GetData() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Model\SQLDB.cs:line 27
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-01-17T15:28:38.1763113+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 28060.6064ms 500 text/html; charset=utf-8
2018-01-17T15:28:38.2383811+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 22562.6913ms 500 text/html; charset=utf-8
2018-01-17T15:28:38.2933471+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:28:38.3017943+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 8.4509ms 200 
2018-01-17T15:36:45.0005747+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T15:36:48.0341115+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T15:36:48.1676931+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 162.5621ms 200 
2018-01-17T15:36:48.2030375+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:36:48.2212455+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 14.9419ms 200 
2018-01-17T15:38:40.3424133+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T15:38:43.0901802+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T15:38:43.1785568+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 94.3459ms 200 
2018-01-17T15:38:43.2220622+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:38:43.2468386+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 23.3246ms 200 
2018-01-17T15:38:57.5906318+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:38:57.6580644+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:38:57.6747608+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:39:02.0498560+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:39:04.4656557+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:39:05.7574134+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:39:49.1697369+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 51514.924ms
2018-01-17T15:39:49.1697172+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 45324.9569ms
2018-01-17T15:39:49.1797572+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.ArgumentOutOfRangeException: The SqlDbType enumeration value, 0, is invalid.
Parameter name: SqlDbType
   at System.Data.SqlClient.MetaType.GetSqlDataType(Int32 tdsType, UInt32 userType, Int32 length)
   at System.Data.SqlClient.TdsParser.TryCommonProcessMetaData(TdsParserStateObject stateObj, _SqlMetaData col)
   at System.Data.SqlClient.TdsParser.TryProcessMetaData(Int32 cColumns, TdsParserStateObject stateObj, _SqlMetaDataSet& metaData)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at SCPersonalizationGraph.Model.SQLDB.<GetData>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Model\SQLDB.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-01-17T15:39:49.1801764+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.ArgumentOutOfRangeException: The SqlDbType enumeration value, 0, is invalid.
Parameter name: SqlDbType
   at System.Data.SqlClient.MetaType.GetSqlDataType(Int32 tdsType, UInt32 userType, Int32 length)
   at System.Data.SqlClient.TdsParser.TryCommonProcessMetaData(TdsParserStateObject stateObj, _SqlMetaData col)
   at System.Data.SqlClient.TdsParser.TryProcessMetaData(Int32 cColumns, TdsParserStateObject stateObj, _SqlMetaDataSet& metaData)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at SCPersonalizationGraph.Model.SQLDB.<GetData>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Model\SQLDB.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-01-17T15:39:49.6106973+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 52019.4386ms 500 text/html; charset=utf-8
2018-01-17T15:39:49.7212926+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 47670.9774ms 500 text/html; charset=utf-8
2018-01-17T15:39:49.7698982+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:39:49.8409702+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 71.1729ms 200 
2018-01-17T15:45:26.1341130+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T15:45:29.0155877+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T15:45:29.1094539+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 99.9499ms 200 
2018-01-17T15:45:29.1427093+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:45:29.1489295+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 5.4835ms 200 
2018-01-17T15:45:40.2557609+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:45:40.3215999+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:45:40.3334004+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:46:10.9188966+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T15:46:10.9693624+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 30649.2179ms
2018-01-17T15:46:10.9775011+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 30721.5285ms 200 application/json; charset=utf-8
2018-01-17T15:46:16.1139387+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:46:16.1206920+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 5.1322ms 200 
2018-01-17T15:46:21.7339772+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:46:21.7397084+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:46:21.7434814+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:46:41.2081800+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T15:46:41.2139020+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 19474.179ms
2018-01-17T15:46:41.2236625+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 19489.5189ms 200 application/json; charset=utf-8
2018-01-17T15:46:41.2372391+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:46:41.2630707+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 25.8361ms 200 
2018-01-17T15:46:44.9934289+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:46:45.0002457+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:46:45.0058098+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:46:49.6026822+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T15:46:49.6087350+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 4608.441ms
2018-01-17T15:46:49.6156497+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4622.2101ms 200 application/json; charset=utf-8
2018-01-17T15:46:49.6348943+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:46:49.6555899+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 20.8428ms 200 
2018-01-17T15:53:18.4170380+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T15:53:21.4262257+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T15:53:21.5701740+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 160.9377ms 200 
2018-01-17T15:53:21.6008059+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:53:21.6052856+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 4.259ms 200 
2018-01-17T15:53:26.5005149+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T15:53:26.7061813+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T15:53:26.7562871+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T15:53:48.7165343+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T15:53:48.7803023+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 22078.7376ms
2018-01-17T15:53:48.7880342+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 22287.3736ms 200 application/json; charset=utf-8
2018-01-17T15:53:48.8081373+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T15:53:48.8157768+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 5.6395ms 200 
2018-01-17T16:07:59.6194092+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T16:08:02.3090224+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T16:08:02.3948683+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 91.8199ms 200 
2018-01-17T16:08:02.4301847+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:08:02.4355454+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 5.3205ms 200 
2018-01-17T16:08:06.4381990+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T16:08:06.5047145+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T16:08:06.5211222+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T16:08:53.1130234+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T16:08:53.2007890+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 46693.0653ms
2018-01-17T16:08:53.2065193+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 46768.6528ms 200 application/json; charset=utf-8
2018-01-17T16:08:53.2490069+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:08:53.2580250+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 8.6021ms 200 
2018-01-17T16:09:39.2002486+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T16:09:39.2070400+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T16:09:39.2124245+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T16:09:42.4878017+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T16:09:42.4943566+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 3287.2038ms
2018-01-17T16:09:42.5132275+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 3312.9709ms 200 application/json; charset=utf-8
2018-01-17T16:09:42.5966737+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:09:42.6170557+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 20.3825ms 200 
2018-01-17T16:10:32.8680101+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T16:10:35.8762790+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T16:10:36.0339002+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 168.5072ms 200 
2018-01-17T16:10:36.1127242+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:10:36.1240707+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 11.3639ms 200 
2018-01-17T16:10:39.7363528+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T16:10:39.8112809+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T16:10:39.8264822+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T16:10:40.1134885+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T16:10:40.2028374+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 392.0583ms
2018-01-17T16:10:40.2141775+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 477.8124ms 200 application/json; charset=utf-8
2018-01-17T16:10:40.2958372+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:10:40.3072586+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 11.4029ms 200 
2018-01-17T16:15:55.3524885+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T16:15:58.3138109+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T16:15:58.4401390+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 154.1139ms 200 
2018-01-17T16:15:58.5022403+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:15:58.5139263+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 12.7921ms 200 
2018-01-17T16:16:05.1275214+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T16:16:05.2007146+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T16:16:05.2124765+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T16:16:05.6064394+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 408.7542ms
2018-01-17T16:16:05.6122432+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'as'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at SCPersonalizationGraph.Model.SQLDB.<GetSummaryByDate>d__3.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Model\SQLDB.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:3431de91-9aa4-487f-907b-f5fe59fad4f4
Error Number:156,State:1,Class:15
2018-01-17T16:16:05.9534536+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T16:16:05.9597077+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T16:16:05.9661636+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T16:16:06.0704974+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 110.9412ms
2018-01-17T16:16:06.0750319+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'as'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at SCPersonalizationGraph.Model.SQLDB.<GetSummaryByDate>d__3.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Model\SQLDB.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:3431de91-9aa4-487f-907b-f5fe59fad4f4
Error Number:156,State:1,Class:15
2018-01-17T16:16:06.2114504+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 1083.948ms 500 text/html; charset=utf-8
2018-01-17T16:16:06.5940800+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 640.5834ms 500 text/html; charset=utf-8
2018-01-17T16:16:06.6386534+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:16:06.6527707+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 7.9966ms 200 
2018-01-17T16:16:20.4659139+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T16:16:20.4720200+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T16:16:20.4786306+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T16:16:20.5730339+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 101.0474ms
2018-01-17T16:16:20.5792324+08:00 [ERR] (SerilogSample/LT-MDA2-T-MY) An unhandled exception has occurred while executing the request
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'as'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at SCPersonalizationGraph.Model.SQLDB.<GetSummaryByDate>d__3.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Model\SQLDB.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SCPersonalizationGraph.Controllers.GraphController.<Get>d__2.MoveNext() in C:\Arif\Hackathone\PersonalizationGrpah\SCPersonalizationGraph\SCPersonalizationGraph\Controllers\GraphController.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:3431de91-9aa4-487f-907b-f5fe59fad4f4
Error Number:156,State:1,Class:15
2018-01-17T16:16:21.0878797+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 621.9942ms 500 text/html; charset=utf-8
2018-01-17T16:16:21.1891617+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:16:21.2419518+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 52.8ms 200 
2018-01-17T16:17:09.4877653+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T16:17:12.1457829+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T16:17:12.2671781+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 136.9293ms 200 
2018-01-17T16:17:12.3274004+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:17:12.3360578+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 8.4857ms 200 
2018-01-17T16:17:16.2982688+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T16:17:16.3889495+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T16:17:16.4081497+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T16:17:16.8584558+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T16:17:16.9509741+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 559.9331ms
2018-01-17T16:17:16.9551194+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 657.0045ms 200 application/json; charset=utf-8
2018-01-17T16:17:17.1546547+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:17:17.1805516+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 23.9558ms 200 
2018-01-17T16:18:48.7333779+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) User profile is available. Using '"C:\Users\mda.DK\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2018-01-17T16:18:51.6147140+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/  
2018-01-17T16:18:51.7065423+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 98.2217ms 200 
2018-01-17T16:18:51.7750829+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:18:51.7899294+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 14.6399ms 200 
2018-01-17T16:18:54.6367170+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/api/graph  
2018-01-17T16:18:54.7289885+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) GraphController: loaded
2018-01-17T16:18:54.7436767+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing action method "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" with arguments (null) - ModelState is Valid
2018-01-17T16:18:55.0855889+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-01-17T16:18:55.1753514+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Executed action "SCPersonalizationGraph.Controllers.GraphController.Get (SCPersonalizationGraph)" in 447.6951ms
2018-01-17T16:18:55.1843756+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 548.206ms 200 application/json; charset=utf-8
2018-01-17T16:18:55.3084666+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request starting HTTP/1.1 GET http://localhost:51085/favicon.ico  
2018-01-17T16:18:55.3187394+08:00 [INF] (SerilogSample/LT-MDA2-T-MY) Request finished in 8.8074ms 200 
